### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by jhdcruz** [jhdcruz/aris#11]
## Logo

- [squircle](https://upload.wikimedia.org/wikipedia/commons/thumb/5/58/Squircle2.svg/800px-Squircle2.svg.png) shape
- 32-bit color

## Sizes

- 72x72
- 48x48
- 96x96
- 144x144
- 192x192

## Deliverables

- `.xml` export format
- `.webp` of the above sizes

> You can use this for `.webp` conversion: https://convertio.co/image-converter/

## Submission

Place inside: **(same filenames)**

```bash
app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp      # 192x192
app/src/main/res/mipmap-hdpi/ic_launcher_round.webp         # 72x72
app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp       # 144x144
app/src/main/res/mipmap-mdpi/ic_launcher_round.webp         # 48x48
app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp        # 96x96
app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml    # XML export
```

**Comment by Yuki000h** [comment]
720 x 720 original dimensions png compressed into 43kb

**Comment by Yuki000h** [comment]
![Aris logo design](https://user-images.githubusercontent.com/103256391/163810700-a51c2e26-0ceb-4058-bbca-d69c74856a9d.png)
